version: '3.1'
services:

  check-service:
    build: hunt_check_service
    image: check-service
    container_name: check-service-container
    ports:
      - "9090:9090"
    depends_on:
      - main-service
      - hunt-db

    environment:
      - SERVICE_URL=http://main-service:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hunt-db:5432/hunt


  hunt-db:
    image: postgres:14-alpine
    container_name: hunt-db-container
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=hunt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=CHS2t1062


  main-service:
    build: hunt_main_service/server
    image: hunt-main-service
    container_name: main-service-container
    ports:
      - "8080:8080"
    depends_on:
      - hunt-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://hunt-db:5432/hunt



